import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "@/shared/components/Navbar"
import Footer from "@/shared/components/Footer"
import { ToastContainer } from "react-toastify" // Importa ToastContainer
import "react-toastify/dist/ReactToastify.css" // Importa los estilos de Toastify
import { Slide } from "react-toastify" // Importa la animación Slide

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Verificamos si estamos en la ruta de landing
  const isLandingPage =
    typeof window !== "undefined" && window.location.pathname === "/landing"

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          {!isLandingPage && <Navbar />}
          <main className="flex-grow">{children}</main>
          {!isLandingPage && <Footer />}
        </div>
        {/* Configuración de ToastContainer */}
        <ToastContainer
          position="top-right"
          autoClose={2000}
          limit={1}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss={false}
          draggable={false}
          pauseOnHover
          theme="light"
          transition={Slide}
        />
      </body>
    </html>
  )
}
